from .music_label.album import Album
from .music_label.author import Author
from .music_label.genre import Genre
from .music_label.music_label import MusicLabel
from .music_label.playlist import Playlist
from .music_label.song import Song
from .music_label.user import User
from .music_label.playlist_has_user import PlaylistUserAssociation
from .music_label.song_has_playlists import SongPlaylistAssociation
from .music_label.song_in_playlist import SongInPlaylist
from .music_label.user_has_song import UserSongAssociation
